// apps/sample10/driver is used to test the output of the code generated by this file.
// To generate fk_gen.h used in apps/sample10/driver:
// $ ./build/sample10 deps/pinocchio/models/baxter_simple.urdf apps/sample10/fk_gen.h
#include "backend.h"
#include "spatial_algebra.h"
#include "utils.h"

#include "blocks/block_visitor.h"
#include "blocks/c_code_generator.h"
#include "builder/builder_base.h"
#include "builder/builder_context.h"
#include "builder/dyn_var.h"
#include "builder/forward_declarations.h"
#include "Eigen/Dense"
#include "builder/static_var.h"
#include "builder/lib/utils.h"

// ignore unused header warning in IDE, this is needed
#include "assert.h"
#include <string>

using builder::dyn_var;
using builder::static_var;
using ctup::Xform;
using ctup::EigenMatrix;



dyn_var<EigenMatrix<double>> fk() {
  dyn_var<EigenMatrix<double>> X_T (6,6);
  dyn_var<EigenMatrix<double>> X_1 (16,36);
  dyn_var<EigenMatrix<double>> X_2 (16,36);

  X_1.setZero();

  static_var<int> i;
  for(i=0;i<36;i=i+1){
    X_2.col(0) = ((dyn_var<builder::eigen_vectorXd_t>)(builder::cast)X_1.col(0)).cos();

    X_2.col(i) =  X_1.col(0+6*(i/6)) * X_T.coeffRef(0,i%6);
    X_2.col(i) += X_1.col(1+6*(i/6)) * X_T.coeffRef(1,i%6);
    X_2.col(i) += X_1.col(2+6*(i/6)) * X_T.coeffRef(2,i%6);
    X_2.col(i) += X_1.col(3+6*(i/6)) * X_T.coeffRef(3,i%6);
    X_2.col(i) += X_1.col(4+6*(i/6)) * X_T.coeffRef(4,i%6);
    X_2.col(i) += X_1.col(5+6*(i/6)) * X_T.coeffRef(5,i%6);
  }

  return X_2;
}

int main(int argc, char* argv[]) {
  const std::string header_filename = (argc <= 1) ? "./fk_gen.h" : argv[1];
  std::cout << header_filename << "\n";

  std::ofstream of(header_filename);
  block::c_code_generator codegen(of);

  of << "#include \"Eigen/Dense\"\n\n";
  of << "#include <iostream>\n\n";
  of << "namespace ctup_gen {\n\n";

  of << "void print_string(const char* str) {\n";
  of << "  std::cout << str << \"\\n\";\n";
  of << "}\n\n";

  of << "template<typename Derived>\n";
  of << "void print_matrix(const Eigen::MatrixBase<Derived>& matrix) {\n";
  of << "  std::cout << matrix << \"\\n\";\n";
  of << "}\n\n";

  builder::builder_context context;

  auto ast = context.extract_function_ast(fk, "fk");
  ast->dump(std::cout, 0);
  block::c_code_generator::generate_code(ast, of, 0);

  of << "}\n";
}
