// apps/sample10/driver is used to test the output of the code generated by this file.
// To generate fk_gen.h used in apps/sample10/driver:
// $ ./build/sample10 deps/pinocchio/models/baxter_simple.urdf apps/sample10/fk_gen.h
#include "backend.h"
#include "spatial_algebra.h"
#include "utils.h"

#include "blocks/block_visitor.h"
#include "blocks/c_code_generator.h"
#include "builder/builder_base.h"
#include "builder/builder_context.h"
#include "builder/dyn_var.h"
#include "builder/forward_declarations.h"
#include "builder/static_var.h"
#include "builder/lib/utils.h"

#include "Eigen/Dense"
#include <Eigen/src/Core/IO.h>
#include <Eigen/src/Core/Matrix.h>
#include <string>
#define CAST_TO_EIGEN_MATRIX (dyn_var<ctup::EigenMatrix<double>>)(builder::cast)

using builder::dyn_var;
using builder::static_var;

using ctup::Xform;

static dyn_var<ctup::EigenMatrix<double>> fk() {
  dyn_var<ctup::EigenMatrix<double,16,1>[]> X_1;
  dyn_var<ctup::EigenMatrix<double,16,1>[]> X_2;
  dyn_var<ctup::EigenMatrix<double,16,1>[]> X_pi;

  resize_arr(X_1, 36);
  resize_arr(X_2, 36);
  resize_arr(X_pi, 36);

  static_var<int> i = 0;
  static_var<int> j = 0;
  static_var<int> l = 0;

  for (i = 0; i < 36; i = i+1)
    (CAST_TO_EIGEN_MATRIX X_pi[i]).setZero();

  for (l=0; l < 6; l = l+1) {
    for (i = 0; i < 6; i = i+1) {
      for (j = 0; j < 6; j = j+1) {
          X_pi[i*6+j]  +=  X_1[i*6+l]*X_2[l*6+j];
      }
    }
  }

  dyn_var<ctup::EigenMatrix<double>> final_ans;
  return final_ans;
}

int main(int argc, char* argv[]) {
  const std::string header_filename = (argc <= 1) ? "./fk_gen.h" : argv[1];
  std::cout << header_filename << "\n";

  std::ofstream of(header_filename);
  block::c_code_generator codegen(of);

  of << "// clang-format off\n\n";
  of << "#include \"Eigen/Dense\"\n\n";
  of << "#include <iostream>\n\n";
  of << "namespace ctup_gen {\n\n";

  of << "static void print_string(const char* str) {\n";
  of << "  std::cout << str << \"\\n\";\n";
  of << "}\n\n";

  of << "template<typename Derived>\n";
  of << "static void print_matrix(const Eigen::MatrixBase<Derived>& matrix) {\n";
  of << "  std::cout << matrix << \"\\n\";\n";
  of << "}\n\n";

  builder::builder_context context;

  auto ast = context.extract_function_ast(fk, "fk");
  block::c_code_generator::generate_code(ast, of, 0);

  of << "}\n";
}
